askyourcandidate/urls.py
from django.conf import settings
from django.urls import re_path as url, include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^login/$', auth_views.LoginView.as_view(), name="login"),
    url('^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url('^change-password/$', auth_views.PasswordChangeView.as_view(), name="change_password"),
    url('^password-change-done/$', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('', include('questions.urls', namespace="questions")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import re_path as url

from questions.views import QuestionList, AskQuestion, QuestionDetail, CandidateDetail, CandidateAnswerQuestion, \
    CandidateList, CandidateRedirect, DespreSite

app_name = 'questions'

urlpatterns = [
        url(r'^$', QuestionList.as_view(), name="index"),
        url(r'question/ask/$', AskQuestion.as_view(), name="question_ask"),
        url(r'question/(?P<pk>\d+)/$', QuestionDetail.as_view(), name="question_detail"),
        url(r'candidate/(?P<pk>\d+)/$', CandidateDetail.as_view(), name="candidate_detail"),
        url(r'candidate/$', CandidateList.as_view(), name="candidate_list"),
        url(r'candidate/own/$', CandidateRedirect.as_view(), name="candidate_redirect"),
        url(r'question/(?P<pk>\d+)/answer/$', CandidateAnswerQuestion.as_view(), name="question_answer"),
        url(r'despre/$', DespreSite.as_view(), name="despre"),
    ]

questions/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Question(models.Model):
    PENDING = 0
    APPROVED = 1
    DECLINED = 2

    STATUS_INTREBARE = (
        (PENDING, 'In asteptare'),
        (APPROVED, 'Aprobata'),
        (DECLINED, 'Respinsa'),
    )
    text = models.CharField(max_length=2048, verbose_name="Intrebarea")
    timestamp = models.DateTimeField(auto_now_add=True)
    owner_oncr_id = models.CharField(max_length=255, verbose_name="ONCR ID", help_text="Dacă nu îți cunoști ONCR ID-ul, întreabă-ți liderul sau șeful de Centru Local. Completând acest câmp îți dai acordul ca numele și Centrul tău Local să fie afișate public, alături de întrebarea ta.")

    owner_name = models.CharField(max_length=255, null=True, blank=True)
    owner_affiliation = models.CharField(max_length=1024, null=True, blank=True)

    approval_status = models.SmallIntegerField(default=PENDING, choices=STATUS_INTREBARE)
    rejection_reason = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.text


class Candidate(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    oncr_id = models.CharField(max_length=20)
    pdf_link = models.URLField()
    motivation = models.TextField()

    photo = models.ImageField(upload_to="img")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    order = models.IntegerField(default=1)

    class Meta:
        ordering = ["order", ]

    def __str__(self):
        return self.name


class CandidateAnswer(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, models.CASCADE)

    timestamp = models.DateTimeField(auto_now=True)
    text = models.TextField(verbose_name="Raspunsul tau")

    class Meta:
        unique_together = ['candidate', 'question']

    def __str__(self):
        return "[{}] {}".format(self.candidate, self.text)

questions/forms.py
from django_recaptcha.fields import ReCaptchaField
from django.conf import settings
from django.core.exceptions import ValidationError
from django.forms import ModelForm, CharField, Textarea
from django_recaptcha.widgets import ReCaptchaV3, ReCaptchaV2Checkbox

from questions.models import CandidateAnswer, Question
from utils.oncr_client import ONCRClient


class QuestionForm(ModelForm):
    class Meta:
        fields = ['text', 'owner_oncr_id']
        model = Question

    text = CharField(required=True, widget=Textarea, label="Intrebarea")
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.oncr_data = {}

    def clean_owner_oncr_id(self):
        # client = ONCRClient(user=settings.ONCR_USER, password=settings.ONCR_PASSWORD)
        # client.do_login()
        import requests
        baseURL = 'https://membri.scout.ro'
        searchURL = '/api/v1/search-user/'

        headers = {"API-Token": settings.ORGO_APIKEY}
        try:
            users = requests.get("{}{}{}".format(baseURL, searchURL, self.cleaned_data["owner_oncr_id"].upper()), headers=headers)
            detailURL = users.json()[0].get("@id")

            data = requests.get("{}{}".format(baseURL, detailURL), headers=headers)
            groupURL = data.json().get("localCenter").get("@id")

            group = requests.get("{}{}".format(baseURL, groupURL), headers=headers)
            self.oncr_data = {
                "fullName": data.json().get("fullName"),
                "groupName": " ".join((data.json().get("localCenter").get("name"), group.json().get("town").get("name")))
            }

        except Exception:
            raise ValidationError("Nu am gasit un membru cu acest ID")

        return self.cleaned_data['owner_oncr_id']

class CandidateAnswerForm(ModelForm):
    class Meta:
        model = CandidateAnswer
        exclude = ["candidate", "question", "timestamp"]

questions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseRedirect, Http404
# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView, RedirectView, TemplateView

from questions.forms import QuestionForm, CandidateAnswerForm
from questions.models import Question, Candidate, CandidateAnswer


class QuestionList(ListView):
    template_name = "questions/question_list.html"
    model = Question

    def dispatch(self, request, *args, **kwargs):
        self.list_type = int(self.request.GET.get("list_type", Question.APPROVED))
        return super(QuestionList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(QuestionList, self).get_queryset().filter(approval_status=self.list_type).order_by("timestamp")

    def get_context_data(self, **kwargs):
        data = super(QuestionList, self).get_context_data(**kwargs)
        data['rejected_count'] = Question.objects.filter(approval_status=Question.DECLINED).count()
        data['pending_count'] = Question.objects.filter(approval_status=Question.PENDING).count()
        data['approved_count'] = Question.objects.filter(approval_status=Question.APPROVED).count()

        data['list_type'] = self.list_type
        return data


class CandidateList(ListView):
    template_name = "questions/candidate_list.html"
    model = Candidate


class QuestionDetail(DetailView):
    template_name = "questions/question_detail.html"
    model = Question

    def get_queryset(self):
        return super(QuestionDetail, self).get_queryset().filter(approval_status=Question.APPROVED).order_by("timestamp")

    def get_context_data(self, **kwargs):
        data = super(QuestionDetail, self).get_context_data(**kwargs)
        candidates = Candidate.objects.all()
        answers_dict = {a.candidate_id: a for a in CandidateAnswer.objects.filter(question=self.object)}
        qa = {c: answers_dict.get(c.id) for c in candidates}
        data["qa"] = qa
        return data


class CandidateDetail(DetailView):
    template_name = "questions/candidate_detail.html"
    model = Candidate

    def get_context_data(self, **kwargs):
        data = super(CandidateDetail, self).get_context_data(**kwargs)
        questions = Question.objects.filter(approval_status=Question.APPROVED).order_by("timestamp")
        answers_dict = {a.question_id: a for a in CandidateAnswer.objects.filter(candidate=self.object)}
        qa = {q: answers_dict.get(q.id) for q in questions}
        data["qa"] = qa
        return data


class CandidateAnswerQuestion(UserPassesTestMixin, UpdateView):
    template_name = "questions/answer_form.html"
    model = CandidateAnswer
    form_class = CandidateAnswerForm

    def test_func(self):
        try:
            return self.request.user.candidate is not None
        except Exception:
            return False

    def get_object(self, queryset=None):
        try:
            pk = self.kwargs.get(self.pk_url_kwarg)
            try:
                self.question = Question.objects.get(pk=pk)
                self.object, created = CandidateAnswer.objects.get_or_create(question=self.question, candidate=self.request.user.candidate)
                return self.object
            except Question.DoesNotExist:
                raise Http404("Question does not exists")
        except AttributeError:
            return None

    def form_valid(self, form):
        self.object = form.save(commit=True)
        messages.success(self.request, "Raspunsul tau a fost salvat!")
        return HttpResponseRedirect(reverse("questions:candidate_detail", kwargs={"pk": self.object.candidate_id}))

    def get_context_data(self, **kwargs):
        data = super(CandidateAnswerQuestion, self).get_context_data(**kwargs)
        data['question'] = self.question
        return data


class AskQuestion(CreateView):
    template_name = "questions/question_form.html"
    model = Question
    form_class = QuestionForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.approval_status = False

        if form.oncr_data:
            self.object.owner_name = form.oncr_data.get("fullName")
            self.object.owner_affiliation = form.oncr_data.get("groupName")

        self.object.save()
        messages.success(self.request, "Intrebarea ta a fost salvata si a mers spre aprobare")
        return HttpResponseRedirect(reverse("questions:index"))


class CandidateRedirect(UserPassesTestMixin, RedirectView):
    def test_func(self):
        try:
            return self.request.user.candidate is not None
        except Exception:
            return False

    def get_redirect_url(self, *args, **kwargs):
        return reverse("questions:candidate_detail", kwargs={"pk": self.request.user.candidate.pk})


class DespreSite(TemplateView):
    template_name = "questions/despre.html"

questions/templates/questions/answer_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load icons %}



{% block title %}
    {{ question }}
{% endblock %}

{% block content %}
    {% if question.owner_affiliation and question.owner_name %}
        <p class = "lead">de la {{ question.owner_name }}, {{ question.owner_affiliation }}</p>
    {% endif %}
    <form action="" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          {% icon "star" %} Trimite
        </button>
      {% endbuttons %}
    </form>
{% endblock %}

questions/templates/questions/candidate_detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">{{ object }}</h1>
        <p class="lead">
            <img src="{{ object.photo.url }}" alt="{{ object.name }}" class="w-25 float-left mr-3 img-thumbnail ">
            <strong>Motivație</strong>: {{ object.motivation }}

        </p>
        <hr class="my-4">
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ object.pdf_link }}" role="button">Formularul de candidatură</a>
        </p>
    </div>

    <ul class = "list-group">
    {% for q, a in qa.items %}
        <li class = "list-group-item">
        <h2>{{ q.text }}</h2>
        {% if q.owner_name and q.owner_affiliation %}
            <p>întrebare de la {{ q.owner_name }}, {{ q.owner_affiliation }}</p>
        {% endif %}

        {% if user.is_authenticated and user.candidate == object %}
            <a class="btn btn-sm btn-outline-secondary" href = "{% url "questions:question_answer" pk=q.id %}">Răspunde / editează răspunsul</a><br>
        {% endif %}
        <small style="color: gray">Ultima actualizare la {{ a.timestamp | date:"d.m.Y H:i" }}</small>
        <p>
            {% if a %}
                <p>{{ a.text|linebreaks }}</p>
            {% else %}
                <div class="alert alert-danger" role="alert">
                    Candidatul nu a răspuns la această întrebare.
                </div>
            {% endif %}
        </p>
        <a class="btn btn-sm btn-outline-secondary" href = "{% url "questions:question_detail" pk=q.id %}">Toate răspunsurile acestei întrebări</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

questions/templates/questions/candidate_list.html
{% extends 'base.html' %}

{% block title %}
    Candidați
{% endblock %}

{% block content %}
    <div>
    {% for c in object_list %}
        <div class="d-inline-flex p-2 mr-4 mt-4 card" style="width: 18rem;">
          <img class="card-img-top" src="{{ c.photo.url }}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ c.name }}</h5>
            <p class="card-text">{{ c.motivation | truncatewords:20 }}</p>
            <a href="{% url "questions:candidate_detail" pk=c.id %}" class="btn btn-primary">Răspunsurile candidatului <span class="badge badge-light">{{ c.candidateanswer_set.count }}</span></a>
          </div>
        </div>

    {% endfor %}
    </div>
    <div style="height: 20px"></div>

{% endblock %}

questions/templates/questions/despre.html
{% extends "base.html" %}

{% block title %}Despre acest site{% endblock %}
{% block content %}
    <p class = "lead">În dorința de a ne asigura că știm pe cine alegem, am considerat că un pas spre transparență este această platformă unde pot fi adresate întrebări către (toți) candidații la Consiliul Director</p>
    <p></p>
{% endblock %}

questions/templates/questions/question_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object }}
{% endblock %}

{% block content %}
    {% if object.owner_name %}
        <p class = "lead">de la {{ object.owner_name }}, {{ object.owner_affiliation }}</p>
    {% endif %}

<ul class="list-group">
    {% for c, a in qa.items %}
        <li class="list-group-item">
            <h2>{{ c.name }}</h2>
            {% if user.is_authenticated and user.candidate == c %}
                <a class="btn btn-sm btn-outline-secondary" href = "{% url "questions:question_answer" pk=object.id %}">Răspunde / editează răspunsul</a><br>
            {% endif %}
            <p>
                {% if a %}
                    <small style="color: gray">Ultima actualizare la {{ a.timestamp | date:"d.m.Y H:i" }}</small>
                    <p>{{ a.text|linebreaks }}</p>
                    <a class="btn btn-sm btn-outline-secondary" href = "{% url "questions:candidate_detail" pk=c.id %}">Toate răspunsurile candidatului</a>
                {% else %}
                    <div class="alert alert-danger" role="alert">
                      Candidatul nu a răspuns la această întrebare.
                    </div>
                {% endif %}
            </p>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

questions/templates/questions/question_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load icons %}

{% block title %}
    Întrebarea ta
{% endblock %}

{% block content %}
    <p class = "lead">Dacă ești membru ONCR, poți să-ți folosești codul de membru pentru a propune o întrebare pentru candidați. Verifică înainte să scrii, să nu fi pus altcineva întrebarea. Toate întrebările trec printr-un proces de aprobare manuală, deci întrebarea ta nu va apărea imediat pe site. Întrebarea ta trebuie să se adreseze în egală măsură tuturor candidaților.</p>
    <p>Întrebarea ta ar trebui să fie cât mai bine formulată pentru a permite un răspuns cât mai la subiect, și trebuie să aibă scopul de a-ți clarifica ție (și altora) dacă îi susții pe oricare din candidați. </p>
    <form action="" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% icon 'star' %} Trimite
        </button>
      {% endbuttons %}
    </form>
{% endblock %}

questions/templates/questions/question_list.html
{% extends 'base.html' %}

{% block title %}
    {% if list_type == 1 %}
    Întrebări <span class="badge badge-success">{{ approved_count }}</span>
    {% else %}
        {% if list_type == 0 %}
            Întrebări în așteptare <span class="badge badge-warning">{{ pending_count }}</span>
        {% else %}
            {% if list_type == 2 %}
                Întrebări respinse <span class="badge badge-danger">{{ rejected_count }}</span>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock %}


{% block content %}
    {% if list_type == 1 %}
    <p class = "lead">Puteți găsi aici și întrebările care <a href = "{% url "questions:index" %}?list_type=0">așteaptă aprobare</a> <span class="badge badge-warning">{{ pending_count }}</span>, și cele care <a href = "{% url "questions:index" %}?list_type=2">au fost respinse</a> <span class="badge badge-danger">{{ rejected_count }}</span>.</p>
    <p>Mai jos sunt întrebările care au fost aprobate și la care candidații pot să răspundă. Orice membru ONCR poate <a href = "{% url "questions:question_ask" %}">adresa</a> o întrebare, atâta vreme cât ea este destinată tuturor candidaților, nu este inclusă într-o altă întrebare deja acceptată, și are relevanță pentru crearea profilului candidatului.</p>
    {% else %}
        <p class = "lead">Puteți să vă întoarceți <a href = "{% url "questions:index" %}?list_type=1">aici</a> la lista cu întrebările aprobate.</p>
    {% endif %}

    {% for q in object_list %}
        <h2>{{ q }}</h2>
        <p>
        {% if q.owner_name and q.owner_affiliation %}
            de la {{ q.owner_name }}, {{ q.owner_affiliation }}
        {% endif %}
        </p>
        {%  if list_type == 1 %}
            <p>
                <a class = "btn btn-sm btn-outline-secondary" href = "{% url "questions:question_detail" pk=q.id %}">Vezi răspunsuri <span class="badge badge-light">{{ q.candidateanswer_set.count }}</span></a>
            </p>
        {% else %}
            {% if list_type == 2 %}
                <div class="alert alert-danger" role="alert">
                    <strong>Intrebarea a fost respinsa</strong>: {{ q.rejection_reason }}
                </div>
            {% endif%}
        {% endif %}
    {% endfor %}
{% endblock %}