askyourcandidate/urls.py
from django.conf import settings
from django.urls import re_path as url, include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^login/$', auth_views.LoginView.as_view(), name="login"),
    url('^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url('^change-password/$', auth_views.PasswordChangeView.as_view(), name="change_password"),
    url('^password-change-done/$', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('', include('questions.urls', namespace="questions")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import re_path as url

from questions.views import QuestionList, AskQuestion, QuestionDetail, CandidateDetail, CandidateAnswerQuestion, \
    CandidateList, CandidateRedirect, DespreSite

app_name = 'questions'

urlpatterns = [
        url(r'^$', QuestionList.as_view(), name="index"),
        url(r'question/ask/$', AskQuestion.as_view(), name="question_ask"),
        url(r'question/(?P<pk>\d+)/$', QuestionDetail.as_view(), name="question_detail"),
        url(r'candidate/(?P<pk>\d+)/$', CandidateDetail.as_view(), name="candidate_detail"),
        url(r'candidate/$', CandidateList.as_view(), name="candidate_list"),
        url(r'candidate/own/$', CandidateRedirect.as_view(), name="candidate_redirect"),
        url(r'question/(?P<pk>\d+)/answer/$', CandidateAnswerQuestion.as_view(), name="question_answer"),
        url(r'despre/$', DespreSite.as_view(), name="despre"),
    ]

templates/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static "css/sticky-footer-navbar.css" %}" rel="stylesheet">
    <title>Candidați Consiliul Director ONCR</title>


    <meta property="og:url"                content="http://askyourcandidate.scout.ro" />
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="Q&A cu candidatii la Consiliul Director" />
    <meta property="og:description"        content="O oportunitate de a interactiona direct cu candidatii la Consiliul Director al ONCR inainte de alegerile de pe 21 aprilie." />
    <meta property="og:image"              content="http://askyourcandidate.scout.ro/static/logo_oncr_1.png" />
    <meta property="og:image:width"        content="1657" />
    <meta property="og:image:height"       content="997" />


  </head>
  <body>
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Candidaturi 2024</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class = "nav-link btn btn-sm btn-outline-secondary" href="{% url "questions:question_ask" %}">Pune o întrebare</a>
          </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url "questions:index" %}">Întrebări <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "questions:candidate_list" %}">Candidați</a>
            </li>
          </ul>

          <ul class="navbar-nav mt-2 mt-md-0">
              {% if request.user.is_authenticated %}
                    <li><a class = "nav-item nav-link" href = "{% url "questions:candidate_redirect" %}">{{ user.candidate.name }}</a></li>
                    <li><a class = "nav-item nav-link" href = "{% url "change_password" %}">Schimbă parola</a></li>
                    <li><a class = "nav-item nav-link" href = "" onclick="do_logout()">Logout</a></li>

              {% else %}
                    <li><a class = "nav-item nav-link" href = "{% url "login" %}">Login</a></li>
              {% endif %}
          </ul>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <h1 class="mt-5">{% block title %}Alegeri pentru Consiliul Director{% endblock %}</h1>
        {% bootstrap_messages %}

        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer">
      <div class="container">
          <span class="text-muted">Dezvoltat și găzduit de <a href="https://yetilabs.ro">Yeti Labs</a> &copy; 2024 | Operat de <a href="https://scout.ro">Cercetașii României</a>. <a href = "{% url "questions:despre" %}">Despre acest site</a></span>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        function getCookie(name) {
          let cookie = {};
          document.cookie.split(';').forEach(function(el) {
            let split = el.split('=');
            cookie[split[0].trim()] = split.slice(1).join("=");
          })
          return cookie[name];
        }

        async function do_logout() {
            await fetch("{% url "logout" %}", {
                method: "POST",
                headers: {
                    "X-CSRFTOKEN": getCookie("csrftoken")
                },
                redirect: 'manual'
            }).then(data => data.redirected && window.location.assign("https://" + window.location.host + "/"))
                .catch(err => console.log(err));
        }
    </script>
  </body>
</html>